# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.findButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.findButton.setFont(font)
        self.findButton.setObjectName("findButton")
        self.gridLayout.addWidget(self.findButton, 7, 0, 1, 2)
        self.searchInName = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.searchInName.setFont(font)
        self.searchInName.setObjectName("searchInName")
        self.gridLayout.addWidget(self.searchInName, 3, 0, 1, 1)
        self.textToFind = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textToFind.setFont(font)
        self.textToFind.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textToFind.setObjectName("textToFind")
        self.gridLayout.addWidget(self.textToFind, 6, 0, 1, 2)
        self.selectDirectoryButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.selectDirectoryButton.setFont(font)
        self.selectDirectoryButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.selectDirectoryButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectDirectoryButton.setAutoFillBackground(False)
        self.selectDirectoryButton.setObjectName("selectDirectoryButton")
        self.gridLayout.addWidget(self.selectDirectoryButton, 0, 0, 1, 3)
        self.useRegister = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.useRegister.setFont(font)
        self.useRegister.setObjectName("useRegister")
        self.gridLayout.addWidget(self.useRegister, 4, 0, 1, 1)
        self.extensionSelect = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.extensionSelect.setFont(font)
        self.extensionSelect.setObjectName("extensionSelect")
        self.extensionSelect.addItem("")
        self.gridLayout.addWidget(self.extensionSelect, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileSelect = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fileSelect.setFont(font)
        self.fileSelect.setObjectName("fileSelect")
        self.horizontalLayout.addWidget(self.fileSelect)
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.openFileButton.setFont(font)
        self.openFileButton.setObjectName("openFileButton")
        self.horizontalLayout.addWidget(self.openFileButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.filePreview = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.filePreview.setFont(font)
        self.filePreview.setMouseTracking(True)
        self.filePreview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filePreview.setAcceptDrops(True)
        self.filePreview.setReadOnly(True)
        self.filePreview.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.filePreview.setObjectName("filePreview")
        self.verticalLayout.addWidget(self.filePreview)
        self.gridLayout.addLayout(self.verticalLayout, 6, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFileFinder = QtWidgets.QMenu(self.menubar)
        self.menuFileFinder.setObjectName("menuFileFinder")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFileFinder.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.findButton.setText(_translate("MainWindow", "Найти"))
        self.searchInName.setText(_translate("MainWindow", "Искать в названии файла"))
        self.textToFind.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.selectDirectoryButton.setText(_translate("MainWindow", "Выберите директорию поиска"))
        self.useRegister.setText(_translate("MainWindow", "Учитывать регистр"))
        self.extensionSelect.setItemText(0, _translate("MainWindow", "*.cpp; *.c; *.h"))
        self.label_3.setText(_translate("MainWindow", "Искомый текст"))
        self.openFileButton.setText(_translate("MainWindow", "Открыть файл"))
        self.filePreview.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.menuFileFinder.setTitle(_translate("MainWindow", "FileFinder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
